# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoApp
  pod 'lottie-ios'
  pod 'RAMAnimatedTabBarController'
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
  pod 'XLPagerTabStrip'

end
